### PR TITLE
Fixed caching of errors bug, new `-max-depth` and consistent panic recovery, autoload continue on errors (+Inf...), abandon tinygo, prevent NaN in maps, == works on more types

### LINKED ISSUE #137: == on functions
should work using cachkey as that's what we use anyway for memoization

then might as well allow it for map keys

### LINKED ISSUE #138: floats like +Inf and NaN can't be re-read
possible hack, predefine them

and add `+` as prefix so

nan=1/.0

serialized to

nan=+Inf

works

### PR DESCRIPTION
**Pull request by ldemailly**
- implement `-max-depth` and panic recovery in all Eval variants so infinite recursion, 1/0, etc. are caught
- fixed bug with caching of errors
- make autoload continue on errors (+Inf...) helps with #138 
- abandoning tinygo because https://tinygo.org/docs/reference/lang-support/#recover-builtin is the last straw that broke my back.
- fixed #138 
- fixed  #137

### CODE REVIEW

File: eval/eval_test.go [hunk 1]
```diff
@@ -852,3 +853,35 @@ func TestExtension(t *testing.T) {
...
+
+func TestNaNMapKey(t *testing.T) {
+	s := eval.NewState()
+	_, err := eval.EvalString(s, `nan=0./0.`, false)
+	if err != nil {
+		t.Errorf("should have not errored out just defining NaN, got %v", err)
+	}
+	_, errs, _ := repl.EvalString(`nan=0./0; m={-42.3: "about -42", 42.1:"42.1", nan: "this is NaN"}; println(m)`)
+	if len(errs) != 1 {
+		t.Errorf("should have an error trying to put a nan in map, got %v", errs)
```
Comment (ccoVeille) [inline eval/eval_test.go:881]:
```suggestion
		t.Errorf("should have an error trying to put a NaN in map, got %v", errs)
```

Unless you have something against uppercase in log (but I don't think so, as other error are using NaN

Or maybe you love naan, and made a typo 🤣😂

File: main.go [hunk 2]
```diff
@@ -100,7 +102,8 @@ func Main() int {
 		return log.FErrf("Error initializing extensions: %v", err)
 	}
 	if *commandFlag != "" {
-		res, errs, _ := repl.EvalString(*commandFlag)
+		// return EvalStringWithOption(Options{All: true, ShowEval: true, NoColor: true, Compact: false}, what)
```
Comment (ccoVeille) [inline main.go:105]: Left behind debug?

File: repl/repl.go [hunk 3]
```diff
@@ -71,15 +75,30 @@ func AutoLoad(s *eval.State, options Options) error {
...
+		line := scanner.Text()
+		_, err = eval.EvalString(s, line, false)
+		if err == nil {
+			count++
+		} else {
+			errorCount++
+			errs = append(errs, err)
+			log.Errf("Error loading autoload line %q: %v", line, err)
+		}
 	}
```
Comment (ccoVeille) [inline repl/repl.go:94]:
```suggestion
	for scanner.Scan() {
		line := scanner.Text()
		_, err = eval.EvalString(s, line, false)
		if err == nil {
			count++
			continue
		}

		errorCount++
		errs = append(errs, err)
		log.Errf("Error loading autoload line %q: %v", line, err)
 	}
```

File: repl/repl.go [hunk 4]
```diff
@@ -140,29 +159,28 @@ func EvalString(what string) (string, []string, string) {
...
 	out := &strings.Builder{}
 	s.Out = out
 	s.LogOut = out
 	s.NoLog = true
-	err := AutoLoad(s, o)
-	if err != nil {
-		log.Errf("Error loading autoload file: %v", err)
-	}
-	_, errs, formatted = EvalOne(s, what, out, o)
+	_ = AutoLoad(s, o) // errors already logged
```
Comment (ccoVeille) [inline repl/repl.go:170]: Why returning an error then?

File: repl/repl.go [hunk 5]
```diff
@@ -232,20 +247,24 @@ func Interactive(options Options) int {
...
 				// In addition to raw lines, we also add the single line version to history.
 				log.LogVf("Adding to history: %q", formatted)
 				term.AddToHistory(formatted)
 			}
 			prev = ""
 			term.SetPrompt(PROMPT)
 		}
+		if panicked {
+			log.Errf("%s", errs[0]) // we know there is exactly 1 error in this case, see EvalOne defer.
+		}
```
Comment (ccoVeille) [inline repl/repl.go:267]: I don't get the need for this log as the defer recover already log the error

File: wasm/wasm_main.go [hunk 6]
```diff
@@ -40,7 +51,11 @@ func jsEval(this js.Value, args []js.Value) interface{} {
 		anyErrs[i] = v
 	}
 	result["errors"] = anyErrs
-	result["formatted"] = strings.TrimSuffix(formatted, "\n")
+	fmt := strings.TrimSuffix(formatted, "\n")
```
Comment (ccoVeille) [inline wasm/wasm_main.go:54]: fmt is a package name, I wouldn't shadow it

**Review by ccoVeille — COMMENTED** [review]
With love, Christophe

File: eval/eval.go [hunk 7]
```diff
@@ -247,21 +251,21 @@ func (s *State) evalPrintLogError(node *ast.Builtin) object.Object {
 func (s *State) evalBuiltin(node *ast.Builtin) object.Object {
 	// all take 1 arg exactly except print and log which take 1+.
 	t := node.Type()
-	min := 1
+	minV := 1
```
[the remark this answers is not in the document]
Comment (ldemailly) [reply eval/eval.go:254]: yeah that was a new annoying warning:)

File: README.md [hunk 8]
```diff
@@ -195,6 +195,8 @@ flags:
     	don't execute, just parse and re format the input
   -history file
     	history file to use (default "~/.grol_history")
+  -max-depth int
+    	Maximum interpreter depth (default 100000)
```
[the remark this answers is not in the document]
Comment (ldemailly) [reply README.md:199]: ah yes I increased it because of pi2.gr and didn't update the readme, I probably need to automate updating that section like I do for fortio

File: eval/eval_api.go [hunk 9]
```diff
@@ -78,7 +87,14 @@ func (s *State) UpdateNumSet() (oldvalue, newvalue int64) {
 
 // Does unwrap (so stop bubbling up) return values.
 func (s *State) Eval(node any) object.Object {
+	if s.depth > s.MaxDepth {
+		log.LogVf("max depth %d reached", s.MaxDepth) // will be logged by the panic handler.
```
[the remark this answers is not in the document]
Comment (ldemailly) [reply eval/eval_api.go:91]: it was log.Critf for a while but it's also log critf there so here, closer to where it happens it's logged below the default log level

File: eval/eval_test.go (hunk 1 above)
Comment (ldemailly) [reply eval/eval_test.go:881]: I like naan but yes should be NaN here

File: wasm/wasm_main.go (hunk 6 above)
Comment (ccoVeille) [reply wasm/wasm_main.go:54]: I recommend you enabling "import-shadowing" linter in revive.

Available via golangci-lint

Comment (ldemailly) [reply wasm/wasm_main.go:54]: if you remember I have enable-all already so... it should show up

Comment (ldemailly) [reply wasm/wasm_main.go:54]: oh so it's a non default rule of revive?

Comment (ldemailly) [reply wasm/wasm_main.go:54]: not sure how to add 1 extra without having to specify all the other default, running it by hand once with:
```
linters-settings:
  revive:
    rules:
      - name: import-shadowing
```

Comment (ldemailly) [reply wasm/wasm_main.go:54]: funny it found a few others (like errors and eval) but it doesn't mind this one :-)

File: eval/eval.go [hunk 10]
```diff
@@ -405,6 +409,11 @@ func (s *State) applyFunction(name string, fn object.Object, args []object.Objec
 	s.Out = oldOut
 	output := buf.Bytes()
 	_, _ = s.Out.Write(output)
```
[the remark this answers is not in the document]
Comment (ldemailly) [reply eval/eval.go:411]: not really but then I do in print log a warning (if there are errors writing to Out the logger will likely also fail to write)

[the remark this answers is not in the document]
Comment (ldemailly) [reply eval/eval.go:411]: added

File: README.md (hunk 8 above)
[the remark this answers is not in the document]
Comment (ldemailly) [reply README.md:199]: fixed

File: repl/repl.go (hunk 4 above)
Comment (ldemailly) [reply repl/repl.go:170]: well... still.. maybe there would be a strict mode and you would stop on errors

File: repl/repl.go (hunk 5 above)
Comment (ldemailly) [reply repl/repl.go:267]: you're right, I think it was something to do with showing up on same line as eval but... removed

before
```
$ 0/0
== Parse ==> 0/0
== Eval  ==> 09:07:43.886 [CRI] Caught panic: runtime error: integer divide by zero
09:07:43.886 [ERR] panic: runtime error: integer divide by zero
```

now
```
$ func (){self()}()
== Parse ==> func(){self()}()
== Eval  ==> 09:10:16.289 [CRI] Caught panic: max depth 250000 reached
```

(that's with -parse, without it looks ok)

File: main.go (hunk 2 above)
Comment (ldemailly) [reply main.go:105]: yeah or rather I copied that one from EvalString to see which options were set before

File: wasm/wasm_main.go (hunk 6 above)
Comment (ccoVeille) [reply wasm/wasm_main.go]: You can find the revive default ones in my 03-safe example here

https://github.com/ccoVeille/golangci-lint-config-examples

I have enabled them all and it helped me.

I still have to share a conf about it

File: eval/eval_api.go [hunk 11]
```diff
@@ -78,7 +87,14 @@ func (s *State) UpdateNumSet() (oldvalue, newvalue int64) {
...
+		s.depth = 0
```
[the remark this answers is not in the document]
Comment (ldemailly) [reply eval/eval_api.go:92]: ah I forgot this, somehow not showing in main thread, adding comment now in next PR
