### PR TITLE
ALL_CAPS are now constants. Changed/shared recursive function environment. Fixed bug with macro environment. Added pprof.

### LINKED ISSUE #47: clarify variable scope, as in...
can read from any scope but only write in current one

### LINKED ISSUE #98: make UPPERCASE constants (you can set once but not change)
That would protect PI and E coming in #96

### PR DESCRIPTION
**Pull request by ldemailly**
fixes #98 

https://github.com/grol-io/grol/issues/47#issuecomment-2267631006

fixes #47

Also fixes mix up with macro environment which was incorrectly reusing the full eval.State when it really only needs object.Environment, split the two. 

This showed up as a bug with ==> macro showing up in output even if no macro was defined (because it got PI and E from other MR)

Added `-profile-mem` and `-profile-cpu` options

Figured out regression and saved as examples/pi_perf.gr

Handle tabs in wasm share button

### CODE REVIEW

File: eval/eval.go [hunk 1]
```diff
@@ -427,7 +428,12 @@ func extendFunctionEnv(name string, fn object.Function, args []object.Object) (*
 			name, len(args), n)}
 	}
 	for paramIdx, param := range fn.Parameters {
-		env.Set(param.Value().Literal(), args[paramIdx])
+		oerr := env.Set(param.Value().Literal(), args[paramIdx])
+		log.LogVf("set %s to %s - %s", param.Value().Literal(), args[paramIdx].Inspect(), oerr.Inspect())
+		if oerr.Type() == object.ERROR { // TODO: doesn't trigger
+			oe, _ := oerr.(object.Error)
+			return nil, &oe
```
Comment (ldemailly) [inline eval/eval.go:435]: This doesn't seem to trigger...

File: eval/eval.go [hunk 2]
```diff
@@ -435,8 +441,18 @@ func (s *State) applyFunction(name string, fn object.Object, args []object.Objec
...
 
-func extendFunctionEnv(name string, fn object.Function, args []object.Object) (*object.Environment, *object.Error) {
-	env := object.NewEnclosedEnvironment(fn.Env)
+func extendFunctionEnv(
+	currrentEnv *object.Environment,
+	name string, fn object.Function,
+	args []object.Object,
+) (*object.Environment, *object.Error) {
+	// https://github.com/grol-io/grol/issues/47
+	// fn.Env is "captured state" but for recursion we now parent from current state; eg
```
Comment (ccoVeille) [inline eval/eval.go:450]:
```suggestion
	// fn.Env is "captured state", but for recursion we now parent from current state; eg
```

Is parent used as a verb?

File: eval/eval_test.go [hunk 3]
```diff
@@ -11,6 +11,13 @@ import (
 	"grol.io/grol/parser"
 )
 
+func init() {
+	err := extensions.Init()
+	if err != nil {
+		panic(err)
+	}
+}
```
Comment (ccoVeille) [inline eval/eval_test.go:19]: Nope


```suggestion
func TestMain(m *testing.M) {	
	err := extensions.Init()
	if err != nil {
		panic(err)
	}
	os.Exit(m.Run())
}
```

File: main.go [hunk 4]
```diff
@@ -34,9 +39,22 @@ func Main() int {
...
+		if err != nil {
+			log.Fatalf("can't start cpu profile: %v", err)
+		}
+		log.Infof("Writing cpu profile to %s", *cpuprofile)
+		defer pprof.StopCPUProfile()
+	}
 	err := extensions.Init()
 	if err != nil {
-		log.Fatalf("Error initializing extensions: %v", err)
+		return log.FErrf("Error initializing extensions: %v", err)
```
Comment (ccoVeille) [inline main.go:57]: So FErrf is Fatalf ?

The name could be better

Comment (ccoVeille) [inline main.go:57]: Why using your ferry here, and using Fatalf in previous if block you add

**Review by ccoVeille — APPROVED** [review]
I'm happy you have tests, because it is not a fun PR

File: main.go (hunk 4 above)
Comment (ldemailly) [reply main.go:57]: ?

File: eval/eval_test.go (hunk 3 above)
Comment (ldemailly) [reply eval/eval_test.go:19]: I realize you don't like init() (for good reasons in library or main code) but how is that necessary or different or better for a test package

File: main.go (hunk 4 above)
Comment (ldemailly) [reply main.go:57]: ic you mean why not change all of them, only changed what the linter complained about re defer not to running but probably should be all yes, in theory/for consistency

Comment (ldemailly) [reply main.go:57]: done

File: eval/eval_test.go (hunk 3 above)
Comment (ccoVeille) [reply eval/eval_test.go]: Here it's not only because init, it's because there is something made to prepend things in tests

File: main.go (hunk 4 above)
Comment (ccoVeille) [reply main.go:57]: Thanks

File: eval/eval_test.go (hunk 3 above)
Comment (ldemailly) [reply eval/eval_test.go]: I did anyway :) thx

File: main.go (hunk 4 above)
Comment (ldemailly) [reply main.go:57]: of note there are still a few more log.Fatalf in other functions (like if you fail to pass a valid filename) and it's fine... for now at least (just means some pprof defer won't happen)

File: eval/eval.go [hunk 5]
```diff
@@ -101,19 +100,23 @@ func (s *State) evalPostfixExpression(node *ast.PostfixExpression) object.Object
...
 	}
+	if oerr.Type() == object.ERROR {
+		return oerr
+	}
 	return val
 }
 
 // Doesn't unwrap return - return bubbles up.
-func (s *State) evalInternal(node any) object.Object {
+func (s *State) evalInternal(node any) object.Object { //nolint:funlen // quite a lot of cases.
```
Comment (ccoVeille) [inline eval/eval.go:119]: Maybe you could add a map[type]func(Node) Object 

Then you create one method per type

So evalInternal method will then simply check if there is a func, then call it

File: object/state.go [hunk 6]
```diff
@@ -28,12 +39,58 @@ func (e *Environment) Get(name string) (Object, bool) {
...
 
-func (e *Environment) Set(name string, val Object) Object {
+// Defines constant as all CAPS (with _ ok in the middle) identifiers.
+// Note that we use []byte as all identifiers are ASCII.
+func Constant(name string) bool {
+	for i, v := range name {
+		if i != 0 && v == '_' {
+			continue
+		}
+		if v < 'A' || v > 'Z' {
```
Comment (ccoVeille) [inline object/state.go:49]: Constant may/could also contains number, no?

Comment (ldemailly) [reply object/state.go:49]: well... not right now indeed :) PI2=PI; PI2++ works https://grol.io/?c=PI2=PI+PI2%2B%2BPI2

File: eval/eval.go (hunk 5 above)
Comment (ccoVeille) [reply eval/eval.go:119]: What do you think about this?

Comment (ldemailly) [reply eval/eval.go:119]: Thanks for the reminder, I had skipped that one earlier

If it worked, we'd need to profile it (good that there is `-profile-cpu` now) but I don't think it'd help because you'd need to cast anyway inside each small function (but try and let me know :) ?)

Note that for other types, like token.Type or object.Type an array lookup would be good, as the type fit into 256 and I had started something like that in #93
