### PR TITLE
Adding => for short lambda form. Bug fixes with incomplete maps.

### LINKED ISSUE #135: (possibly) add `=>` for shorter lambdas
eg

```go
x => x*x
```
would be equivalent to
```go
func (x) {x*x}
```

### PR DESCRIPTION
**Pull request by ldemailly**
- Adding => for short form of lambda ( `x => x*2` == `func (x) {x*2}`)
- Fixed crash with incomplete map.
- Fix bug with incomplete input not reported as error when using grol -c / string eval. 
- Earlier review comment tweaks

Fixes #135

### CODE REVIEW

File: eval/eval.go [hunk 1]
```diff
@@ -171,6 +171,11 @@ func (s *State) evalInternal(node any) object.Object { //nolint:funlen,gocyclo /
 			Env:        s.env,
 			Body:       node.Body,
 			Variadic:   node.Variadic,
+			Lambda:     node.IsLambda,
+		}
+		if !fn.Lambda && len(fn.Parameters) == 1 && len(fn.Body.Statements) == 1 && fn.Name == nil {
+			log.LogVf("Normalizing non short lambda form to => lambda")
```
Comment (ccoVeille) [inline eval/eval.go:177]:
```suggestion
			log.LogVf("Normalizing non-short lambda form to => lambda")
```

File: lexer/lexer.go [hunk 2]
```diff
@@ -68,6 +68,10 @@ func (l *Lexer) NextToken() *token.Token {
 			// so we normalize := like it didn't exist.
 			return token.ConstantTokenChar2(ch, nextChar)
 		}
+		if nextChar == '>' && ch == '=' {
```
Comment (ccoVeille) [inline lexer/lexer.go:71]: Maybe you could invert


```suggestion
		if ch == '=' && nextChar == '>' {
```

Or add a comment


```suggestion
		// detecting lamda function ( '=>' )
		if nextChar == '>' && ch == '=' {
```

Or something like that

File: main_test.txtar [hunk 3]
```diff
@@ -204,6 +204,12 @@ stdout '^\[27,28,29,30\]$'
 grol -quiet -c '(23:31)[5-1:23-24]'
 stdout '^\[27,28,29\]$'
 
+# crash on weird half function body
+!grol -quiet -c '(x) {1'
+stderr 'Incomplete input'
+!stderr 'panic'
+!stderr 'runtime error: invalid memor'
```
Comment (ccoVeille) [inline main_test.txtar:211]: Shouldn't be this?

```suggestion
!stderr 'runtime error: invalid memory'
```

File: lexer/lexer.go (hunk 2 above)
Comment (ldemailly) [reply lexer/lexer.go]: I added a comment, the test is in the order it is because ch is already likely to be = (or ! ...) so I want the most specific first and no retest unless needed

File: eval/memo_test.go [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+
+import (
+	"testing"
+
+	"grol.io/grol/eval"
+	"grol.io/grol/object"
+)
+
+func TestBigArrayNotHashable(t *testing.T) {
+	// This test is to make sure that big arrays are no hashable.
```
Comment (ldemailly) [inline eval/memo_test.go:11]:
```suggestion
	// This test is to make sure that big arrays are showing as not hashable (so no crash when used later).
```

**Comment by ldemailly** [comment]
I may bite the bullet and make

(x,y,z) => x+y+z

but that's a big change to the parser

File: token/token.go [hunk 5]
```diff
@@ -114,6 +114,7 @@ const (
 	AND
 	LEFTSHIFT
 	RIGHTSHIFT
+	LAMBDA // => lambda short cut: `a,b => a+b`` alias for `func(a,b) {a+b}``
```
Comment (ccoVeille) [inline token/token.go:117]: I don't get the double backtick, maybe  you wanted this

```suggestion
	LAMBDA // => lambda short cut: `a,b => a+b` alias for `func(a,b) {a+b}`
```

**Review by ccoVeille — APPROVED** [review]
One minor remark, but seems OK

**Comment by ldemailly** [comment]
> One minor remark, but seems OK

you meant awesome :) 

thanks for the reviews!

File: object/object.go [hunk 6]
```diff
@@ -489,6 +489,7 @@ type Function struct {
 	Body       *ast.Statements
 	Env        *Environment
 	Variadic   bool
+	Lambda     bool // no name, 1 param, 1 statement.
```
Comment (ldemailly) [inline object/object.go:492]:
```suggestion
	Lambda     bool // i.e. has no name.
```
